<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net472;net11.0</TargetFrameworks>
        <AssemblyName>SharpHPatchZ.Program</AssemblyName>
        <RootNamespace>SharpHPatchZ.Program</RootNamespace>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Platforms>x64;ARM64;AnyCPU;x86</Platforms>
        <Version>3.0.0</Version>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Configurations>Debug;Release</Configurations>
	    <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\SharpHPatchZ\SharpHPatchZ.csproj" />
    </ItemGroup>
</Project>
