//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.CommandLine.Properties {
    using System;
    using System.Collections.Generic;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    internal class Resources {
        internal static Dictionary<string, string> Locale = new Dictionary<string, string>
        {
            {"ArgumentConversionCannotParse", "Cannot parse argument '{0}' as expected type '{1}'."},
            {"ArgumentConversionCannotParseForCommand", "Cannot parse argument '{0}' for command '{1}' as expected type '{2}'."},
            {"ArgumentConversionCannotParseForOption", "Cannot parse argument '{0}' for option '{1}' as expected type '{2}'."},
            {"CommandExpectsFewerArguments", "Command '{0}' expects no more than {1} arguments, but {2} were provided."},
            {"CommandExpectsOneArgument", "Command '{0}' expects a single argument but {1} were provided."},
            {"CommandNoArgumentProvided", "No argument was provided for Command '{0}'."},
            {"CommandRequiredArgumentMissing", "Required argument missing for command: '{0}'."},
            {"DirectoryDoesNotExist", "Directory does not exist: '{0}'."},
            {"ErrorReadingResponseFile", "Error reading response file '{0}': {1}"},
            {"ExceptionHandlerHeader", "Unhandled exception: "},
            {"FileDoesNotExist", "File does not exist: '{0}'."},
            {"FileOrDirectoryDoesNotExist", "File or directory does not exist: '{0}'."},
            {"HelpAdditionalArgumentsDescription", "Arguments passed to the application that is being run."},
            {"HelpAdditionalArgumentsTitle", "Additional Arguments:"},
            {"HelpArgumentDefaultValueLabel", "default"},
            {"HelpArgumentsTitle", "Arguments:"},
            {"HelpCommandsTitle", "Commands:"},
            {"HelpDescriptionTitle", "Description:"},
            {"HelpOptionDescription", "Show help and usage information"},
            {"HelpOptionsRequiredLabel", "(REQUIRED)"},
            {"HelpOptionsTitle", "Options:"},
            {"HelpUsageAdditionalArguments", "[[--] <additional arguments>...]]"},
            {"HelpUsageCommand", "[command]"},
            {"HelpUsageOptions", "[options]"},
            {"HelpUsageTitle", "Usage:"},
            {"InvalidCharactersInFileName", "Character not allowed in a file name: '{0}'."},
            {"InvalidCharactersInPath", "Character not allowed in a path: '{0}'."},
            {"OptionExpectsFewerArguments", "Option '{0}' expects no more than {1} arguments, but {2} were provided."},
            {"OptionExpectsOneArgument", "Option '{0}' expects a single argument but {1} were provided."},
            {"OptionNoArgumentProvided", "No argument was provided for Option '{0}'."},
            {"OptionRequiredArgumentMissing", "Required argument missing for option: '{0}'."},
            {"RequiredCommandWasNotProvided", "Required command was not provided."},
            {"ResponseFileNotFound", "Response file not found '{0}'."},
            {"SuggestionsTokenNotMatched", "'{0}' was not matched. Did you mean one of the following?"},
            {"UnrecognizedArgument", "Argument '{0}' not recognized. Must be one of:{1}"},
            {"UnrecognizedCommandOrArgument", "Unrecognized command or argument '{0}'."},
            {"VersionOptionCannotBeCombinedWithOtherArguments", "{0} option cannot be combined with other arguments."},
            {"VersionOptionDescription", "Show version information"},
        };

        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.CommandLine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse argument &apos;{0}&apos; as expected type &apos;{1}&apos;..
        /// </summary>
        internal static string ArgumentConversionCannotParse {
            get {
                return Locale["ArgumentConversionCannotParse"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse argument &apos;{0}&apos; for command &apos;{1}&apos; as expected type &apos;{2}&apos;..
        /// </summary>
        internal static string ArgumentConversionCannotParseForCommand {
            get {
                return Locale["ArgumentConversionCannotParseForCommand"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse argument &apos;{0}&apos; for option &apos;{1}&apos; as expected type &apos;{2}&apos;..
        /// </summary>
        internal static string ArgumentConversionCannotParseForOption {
            get {
                return Locale["ArgumentConversionCannotParseForOption"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; expects no more than {1} arguments, but {2} were provided..
        /// </summary>
        internal static string CommandExpectsFewerArguments {
            get {
                return Locale["CommandExpectsFewerArguments"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; expects a single argument but {1} were provided..
        /// </summary>
        internal static string CommandExpectsOneArgument {
            get {
                return Locale["CommandExpectsOneArgument"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No argument was provided for Command &apos;{0}&apos;..
        /// </summary>
        internal static string CommandNoArgumentProvided {
            get {
                return Locale["CommandNoArgumentProvided"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required argument missing for command: &apos;{0}&apos;..
        /// </summary>
        internal static string CommandRequiredArgumentMissing {
            get {
                return Locale["CommandRequiredArgumentMissing"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist: &apos;{0}&apos;..
        /// </summary>
        internal static string DirectoryDoesNotExist {
            get {
                return Locale["DirectoryDoesNotExist"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading response file &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string ErrorReadingResponseFile {
            get {
                return Locale["ErrorReadingResponseFile"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception: .
        /// </summary>
        internal static string ExceptionHandlerHeader {
            get {
                return Locale["ExceptionHandlerHeader"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist: &apos;{0}&apos;..
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return Locale["FileDoesNotExist"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File or directory does not exist: &apos;{0}&apos;..
        /// </summary>
        internal static string FileOrDirectoryDoesNotExist {
            get {
                return Locale["FileOrDirectoryDoesNotExist"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments passed to the application that is being run..
        /// </summary>
        internal static string HelpAdditionalArgumentsDescription {
            get {
                return Locale["HelpAdditionalArgumentsDescription"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Arguments:.
        /// </summary>
        internal static string HelpAdditionalArgumentsTitle {
            get {
                return Locale["HelpAdditionalArgumentsTitle"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        internal static string HelpArgumentDefaultValueLabel {
            get {
                return Locale["HelpArgumentDefaultValueLabel"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments:.
        /// </summary>
        internal static string HelpArgumentsTitle {
            get {
                return Locale["HelpArgumentsTitle"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands:.
        /// </summary>
        internal static string HelpCommandsTitle {
            get {
                return Locale["HelpCommandsTitle"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string HelpDescriptionTitle {
            get {
                return Locale["HelpDescriptionTitle"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show help and usage information.
        /// </summary>
        internal static string HelpOptionDescription {
            get {
                return Locale["HelpOptionDescription"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (REQUIRED).
        /// </summary>
        internal static string HelpOptionsRequiredLabel {
            get {
                return Locale["HelpOptionsRequiredLabel"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options:.
        /// </summary>
        internal static string HelpOptionsTitle {
            get {
                return Locale["HelpOptionsTitle"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[--] &lt;additional arguments&gt;...]].
        /// </summary>
        internal static string HelpUsageAdditionalArguments {
            get {
                return Locale["HelpUsageAdditionalArguments"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [command].
        /// </summary>
        internal static string HelpUsageCommand {
            get {
                return Locale["HelpUsageCommand"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [options].
        /// </summary>
        internal static string HelpUsageOptions {
            get {
                return Locale["HelpUsageOptions"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:.
        /// </summary>
        internal static string HelpUsageTitle {
            get {
                return Locale["HelpUsageTitle"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character not allowed in a file name: &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidCharactersInFileName {
            get {
                return Locale["InvalidCharactersInFileName"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character not allowed in a path: &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidCharactersInPath {
            get {
                return Locale["InvalidCharactersInPath"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; expects no more than {1} arguments, but {2} were provided..
        /// </summary>
        internal static string OptionExpectsFewerArguments {
            get {
                return Locale["OptionExpectsFewerArguments"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; expects a single argument but {1} were provided..
        /// </summary>
        internal static string OptionExpectsOneArgument {
            get {
                return Locale["OptionExpectsOneArgument"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No argument was provided for Option &apos;{0}&apos;..
        /// </summary>
        internal static string OptionNoArgumentProvided {
            get {
                return Locale["OptionNoArgumentProvided"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required argument missing for option: &apos;{0}&apos;..
        /// </summary>
        internal static string OptionRequiredArgumentMissing {
            get {
                return Locale["OptionRequiredArgumentMissing"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required command was not provided..
        /// </summary>
        internal static string RequiredCommandWasNotProvided {
            get {
                return Locale["RequiredCommandWasNotProvided"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response file not found &apos;{0}&apos;..
        /// </summary>
        internal static string ResponseFileNotFound {
            get {
                return Locale["ResponseFileNotFound"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was not matched. Did you mean one of the following?.
        /// </summary>
        internal static string SuggestionsTokenNotMatched {
            get {
                return Locale["SuggestionsTokenNotMatched"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &apos;{0}&apos; not recognized. Must be one of:{1}.
        /// </summary>
        internal static string UnrecognizedArgument {
            get {
                return Locale["UnrecognizedArgument"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized command or argument &apos;{0}&apos;..
        /// </summary>
        internal static string UnrecognizedCommandOrArgument {
            get {
                return Locale["UnrecognizedCommandOrArgument"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} option cannot be combined with other arguments..
        /// </summary>
        internal static string VersionOptionCannotBeCombinedWithOtherArguments {
            get {
                return Locale["VersionOptionCannotBeCombinedWithOtherArguments"];
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show version information.
        /// </summary>
        internal static string VersionOptionDescription {
            get {
                return Locale["VersionOptionDescription"];
            }
        }
    }
}
